imports:
    # bundle admins
    - { resource: '@ImaticDirectoryBundle/Resources/config/admin.yml' }

framework:
    secret:                     test
    test: ~
    session:
        storage_id:             session.storage.filesystem
    form:                       true
    csrf_protection:            true
    validation:
        enabled:                true
        enable_annotations:     true
    translator:
        enabled:                true
    router:
        resource:               %kernel.root_dir%/config/routing.yml
    templating:
        engines:                [twig]
    default_locale:                 cs_CZ

twig:
    debug:                      %kernel.debug%
    strict_variables:           %kernel.debug%

doctrine:
    dbal:
        connections:
            default:
                driver:         pdo_sqlite
                memory:         true
                path:           %kernel.root_dir%/tmp/test.db
#    dbal:
#        default_connection:   default
#        connections:
#            default:
#                driver:   pdo_pgsql
#                host:     localhost
#                port:     5432
#                dbname:   custom_fields
#                user:     developer
#                password: developer
#                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:           true
        resolve_target_entities:
            Imatic\Bundle\DirectoryBundle\Model\AddressInterface: App\Bundle\DirectoryBundle\Entity\Address
            Imatic\Bundle\DirectoryBundle\Model\CompanyInterface: App\Bundle\DirectoryBundle\Entity\Company
            Imatic\Bundle\DirectoryBundle\Model\CompanyPersonInterface: App\Bundle\DirectoryBundle\Entity\CompanyPerson
            Imatic\Bundle\DirectoryBundle\Model\ContactInterface: App\Bundle\DirectoryBundle\Entity\Contact
            Imatic\Bundle\DirectoryBundle\Model\ContactItemInterface: App\Bundle\DirectoryBundle\Entity\ContactItem
            Imatic\Bundle\DirectoryBundle\Model\ContactTypeInterface: App\Bundle\DirectoryBundle\Entity\ContactType
            Imatic\Bundle\DirectoryBundle\Model\EmailInterface: App\Bundle\DirectoryBundle\Entity\Email
            Imatic\Bundle\DirectoryBundle\Model\PersonInterface: App\Bundle\DirectoryBundle\Entity\Person
            Imatic\Bundle\DirectoryBundle\Model\PhoneInterface: App\Bundle\DirectoryBundle\Entity\Phone

monolog:
    handlers:
        main:
          type:                 "null"

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: password
                        roles:  [ROLE_SUPER_ADMIN]

    firewalls:
        main:
            provider:           in_memory
            context:            user
            pattern:            /admin/(.*)
            http_basic:
            anonymous:          false

    access_control:
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

sonata_block:
    default_contexts:           [admin]
    blocks:
        sonata.admin.block.admin_list:
            contexts:           [admin]
